/* Полный бестиарий боссов для Terraria + Calamity 2.2.2.
 * Состав сверяется с официальными страницами Bosses обеих игр:
 * 19 ванильных, 26 обычных Calamity, 4 скрытых Calamity и 5 мини-боссов.
 */
(() => {
  const bosses = [
    { id:"king-slime", era:"pre", type:"Ваниль", name:"Король слизней", en:"King Slime", q:5, art:"assets/boss-sprites/vanilla/king-slime.png", where:"Поверхность или слизневой дождь", when:"Самое начало, когда готовы 200 здоровья и простая арена", summon:"Слизневая корона на алтаре зла либо естественное появление", drops:"Крюк, седло, Ниндзя и полезные стартовые предметы", tip:"Телепортируется к игроку и учит держать свободное место на арене." },
    { id:"desert-scourge", era:"pre", type:"Каламити", name:"Пустынный бич", en:"Desert Scourge", q:6, art:"assets/boss-sprites/desert-scourge.png", where:"Пустыня", when:"Первый босс Calamity", summon:"Используй Пустынный медальон в пустыне", drops:"Жемчужные осколки, морские материалы и раннее оружие", tip:"Не покидай пустыню и подготовь длинную ровную насыпь." },
    { id:"eye-of-cthulhu", era:"pre", type:"Ваниль", name:"Глаз Ктулху", en:"Eye of Cthulhu", q:8, art:"assets/boss-sprites/vanilla/eye-of-cthulhu.png", where:"Поверхность ночью", when:"После первого снаряжения и Пустынного бича", summon:"Подозрительный глаз ночью либо естественное появление", drops:"Щит Ктулху в эксперте, руды зла и оружие", tip:"После победы открывается ранняя ветка кислотного дождя." },
    { id:"crabulon", era:"pre", type:"Каламити", name:"Крабулон", en:"Crabulon", q:9, art:"assets/boss-sprites/crabulon.png", where:"Подземный грибной биом", when:"После Глаза или параллельно", summon:"Используй Росток декаподиты среди светящихся грибов", drops:"Грибное оружие и Грибной сгусток", tip:"Необязательный, но выгодный ранний бой." },
    { id:"eater-of-worlds", era:"pre", type:"Ваниль", name:"Пожиратель миров", en:"Eater of Worlds", q:10, art:"assets/boss-sprites/vanilla/eater-of-worlds.png", where:"Порча", when:"Перед Разумом улья", summon:"Разбей три теневые сферы или используй Еду червя", drops:"Демонит, теневая чешуя и материалы Порчи", tip:"Пронзающее оружие быстро повреждает много сегментов." },
    { id:"brain-of-cthulhu", era:"pre", type:"Ваниль", name:"Мозг Ктулху", en:"Brain of Cthulhu", q:10, art:"assets/boss-sprites/vanilla/brain-of-cthulhu.png", where:"Багрянец", when:"Перед Перфораторами", summon:"Разбей три багряных сердца или используй Кровавый позвоночник", drops:"Кримтан, образцы тканей и материалы Багрянца", tip:"Сначала уничтожь ползунов, затем следи за настоящим Мозгом." },
    { id:"hive-mind", era:"pre", type:"Каламити", name:"Разум улья", en:"The Hive Mind", q:10, art:"assets/boss-sprites/hive-mind.png", where:"Порча", when:"После Пожирателя миров", summon:"Уничтожь опухоль улья либо используй Терратому", drops:"Порченое оружие Calamity и открытие аэролита", tip:"Доступен в мире с Порчей; Перфораторы являются багряной альтернативой." },
    { id:"perforators", era:"pre", type:"Каламити", name:"Перфораторы", en:"The Perforators", q:10, art:"assets/boss-sprites/perforators.png", where:"Багрянец", when:"После Мозга Ктулху", summon:"Уничтожь кисту Перфораторов либо используй Кровавый образец", drops:"Багряное оружие Calamity и открытие аэролита", tip:"Сражение состоит из улья и трёх червей разного размера." },
    { id:"queen-bee", era:"pre", type:"Ваниль", name:"Королева пчёл", en:"Queen Bee", q:11, art:"assets/boss-sprites/vanilla/queen-bee.png", where:"Улей в подземных джунглях", when:"До Скелетрона или Бога слизней", summon:"Разбей личинку либо используй Пчелиную массу", drops:"Пчелиное оружие, воск и аксессуары", tip:"Сохрани стены улья или построй просторную арену в джунглях." },
    { id:"deerclops", era:"pre", type:"Ваниль", name:"Циклоолень", en:"Deerclops", q:11, art:"assets/boss-sprites/vanilla/deerclops.png", where:"Снежный биом ночью", when:"Опционально в середине прехардмода", summon:"Используй Оленью вещь в снегах ночью", drops:"Теневое оружие и предметы Don't Starve", tip:"Бой необязателен для основной прогрессии." },
    { id:"skeletron", era:"pre", type:"Ваниль", name:"Скелетрон", en:"Skeletron", q:11, art:"assets/boss-sprites/vanilla/skeletron.png", where:"Вход в Данж ночью", when:"Поздний прехардмод", summon:"Поговори со стариком у Данжа ночью", drops:"Доступ в Данж, Механик и первый слой Бездны", tip:"Уничтожь руки, затем сосредоточь урон на голове." },
    { id:"slime-god", era:"pre", type:"Каламити", name:"Бог слизней", en:"The Slime God", q:12, art:"assets/boss-sprites/slime-god.png", where:"Любая широкая наземная арена", when:"Последний босс Calamity перед Стеной плоти", summon:"Используй Перегруженный осадок", drops:"Очищенный гель и броня Статиджель", tip:"Два паладина и ядро требуют очень длинной арены." },
    { id:"wall-of-flesh", era:"pre", type:"Ваниль", name:"Стена плоти", en:"Wall of Flesh", q:13, art:"assets/boss-sprites/vanilla/wall-of-flesh.png", where:"Преисподняя, длинный мост", when:"Финал прехардмода", summon:"Брось куклу Гида в лаву, пока Гид жив", drops:"Эмблемы классов, Молот и переход в хардмод", tip:"Двигайся в одном направлении и заранее расчисти весь маршрут." },

    { id:"queen-slime", era:"hard", type:"Ваниль", name:"Королева слизней", en:"Queen Slime", q:14, art:"assets/boss-sprites/vanilla/queen-slime.png", where:"Святые земли", when:"Ранний хардмод", summon:"Используй Кристалл желатина", drops:"Крылья, ездовой слизень и хрустальный набор", tip:"Полезный источник первых хардмодных крыльев." },
    { id:"cryogen", era:"hard", type:"Каламити", name:"Криоген", en:"Cryogen", q:15, art:"assets/boss-sprites/cryogen.png", where:"Снежный биом", when:"До или между механическими боссами", summon:"Используй Крио-ключ в снегах", drops:"Крионитовая руда, Архимаг и ледяное оружие", tip:"Не выходи из снежного биома во время боя." },
    { id:"twins", era:"hard", type:"Ваниль", name:"Близнецы", en:"The Twins", q:16, art:"assets/boss-sprites/vanilla/twins.png", where:"Поверхность ночью", when:"Один из трёх механических боссов", summon:"Используй Механический глаз ночью", drops:"Души зрения и святые слитки", tip:"Не переводи обоих Близнецов во вторую фазу одновременно." },
    { id:"aquatic-scourge", era:"hard", type:"Каламити", name:"Водный бич", en:"Aquatic Scourge", q:16, art:"assets/boss-sprites/aquatic-scourge.png", where:"Сернистое море", when:"После одного механического босса", summon:"Используй Морепродукты в Сернистом море", drops:"Сернистое оружие и второй уровень кислотного дождя", tip:"Строй платформы над водой и используй пронзание." },
    { id:"destroyer", era:"hard", type:"Ваниль", name:"Уничтожитель", en:"The Destroyer", q:16, art:"assets/boss-sprites/vanilla/destroyer.png", where:"Поверхность ночью", when:"Один из трёх механических боссов", summon:"Используй Механического червя ночью", drops:"Души могущества и святые слитки", tip:"Уничтожай зонды и применяй оружие, поражающее несколько сегментов." },
    { id:"brimstone-elemental", era:"hard", type:"Каламити", name:"Серный элементаль", en:"Brimstone Elemental", q:17, art:"assets/boss-sprites/brimstone-elemental.png", where:"Серный кратер", when:"После двух механических боссов", summon:"Используй Обугленный идол в Серном кратере", drops:"Серное оружие и аксессуары", tip:"Отдельная пещерная арена безопаснее обычного адского моста." },
    { id:"skeletron-prime", era:"hard", type:"Ваниль", name:"Скелетрон Прайм", en:"Skeletron Prime", q:16, art:"assets/boss-sprites/vanilla/skeletron-prime.png", where:"Поверхность ночью", when:"Один из трёх механических боссов", summon:"Используй Механический череп ночью", drops:"Души страха и святые слитки", tip:"Сначала убери самые опасные руки, не затягивая бой до рассвета." },
    { id:"calamitas-clone", era:"hard", type:"Каламити", name:"Клон Каламитас", en:"Calamitas Clone", q:18, art:"assets/boss-sprites/calamitas-clone.png", where:"Широкая открытая арена", when:"После ранних хардмодных боссов, до Плантеры", summon:"Используй Око запустения", drops:"Пепел бедствия и открытие солнечной ветки", tip:"Не путай клона с финальной Верховной ведьмой." },
    { id:"plantera", era:"hard", type:"Ваниль", name:"Плантера", en:"Plantera", q:19, art:"assets/boss-sprites/vanilla/plantera.png", where:"Подземные джунгли", when:"После механических боссов и Клона", summon:"Разбей розовую луковицу либо используй переносную луковицу", drops:"Ключ храма и открытие многолетней руды", tip:"Не выводи Плантеру за пределы подземных джунглей." },
    { id:"leviathan-anahita", era:"hard", type:"Каламити", name:"Левиафан и Анахита", en:"Leviathan and Anahita", q:20, art:"assets/boss-sprites/leviathan-anahita.png", where:"Чистый океан", when:"После Плантеры", summon:"Найди и атакуй певицу ??? в синем океане", drops:"Океанское оружие и открытие второго слоя Бездны", tip:"Анахита начинает бой, после чего к ней присоединяется Левиафан." },
    { id:"astrum-aureus", era:"hard", type:"Каламити", name:"Аструм Ауреус", en:"Astrum Aureus", q:21, art:"assets/boss-sprites/astrum-aureus.png", where:"Астральная инфекция ночью", when:"После Плантеры", summon:"Используй Астральный комок ночью", drops:"Ауреусовы клетки и астральное оружие", tip:"Расчисти длинную астральную поверхность до призыва." },
    { id:"golem", era:"hard", type:"Ваниль", name:"Голем", en:"Golem", q:22, art:"assets/boss-sprites/vanilla/golem.png", where:"Храм ящеров", when:"После Плантеры", summon:"Активируй алтарь ящеров Ячейкой питания", drops:"Жуки, Солнечный камень и открытие скории", tip:"В Calamity Голем опаснее ванильного — расширь комнату храма." },
    { id:"duke-fishron", era:"hard", type:"Ваниль", name:"Герцог Рыброн", en:"Duke Fishron", q:23, art:"assets/boss-sprites/vanilla/duke-fishron.png", where:"Чистый океан", when:"Опционально после Плантеры или Голема", summon:"Рыбачь Трюфельным червём в океане", drops:"Цунами, Тайфун, Флайрон и мощные крылья", tip:"Не покидай океан и оставь место для быстрых рывков." },
    { id:"plaguebringer-goliath", era:"hard", type:"Каламити", name:"Чумной голиаф", en:"The Plaguebringer Goliath", q:23, art:"assets/boss-sprites/plaguebringer-goliath.png", where:"Джунгли", when:"После Голема", summon:"Используй Чумную приманку в джунглях", drops:"Заражённые бронепластины и чумное оружие", tip:"Открытая арена над джунглями помогает переживать рывки." },
    { id:"empress-of-light", era:"hard", type:"Ваниль", name:"Императрица света", en:"Empress of Light", q:23, art:"assets/boss-sprites/vanilla/empress-of-light.png", where:"Святые земли", when:"Опционально после Плантеры", summon:"Убей Призматическую кружевницу в Святых землях", drops:"Знак парения, Ночное сияние и Террапризма при дневной победе", tip:"Дневной вариант убивает с одного попадания и предназначен для опытных игроков." },
    { id:"betsy", era:"hard", type:"Ваниль · событие", name:"Бетси", en:"Betsy", q:23, art:"assets/boss-sprites/vanilla/betsy.png", where:"Седьмая волна Армии Древних третьего уровня", when:"После Голема", summon:"Запусти Армию Древних после Голема и защити кристалл до финальной волны", drops:"Гнев Бетси, Воздушная погибель, Летающий дракон и крылья", tip:"Это полноценный событийный босс; одновременно защищай кристалл и уклоняйся от огня." },
    { id:"ravager", era:"hard", type:"Каламити", name:"Разоритель", en:"Ravager", q:23, art:"assets/boss-sprites/ravager.png", where:"Поверхность", when:"После Голема; повторно после Провиденс", summon:"Используй Смертельный тотем", drops:"Мясной геод, материалы сплавов и позднее Кровавик", tip:"Последовательно уничтожай конечности, голову и тело." },
    { id:"lunatic-cultist", era:"hard", type:"Ваниль", name:"Лунатик-культист", en:"Lunatic Cultist", q:24, art:"assets/boss-sprites/vanilla/lunatic-cultist.png", where:"Вход в Данж", when:"После Голема и подготовки к лунным событиям", summon:"Убей четырёх культистов у входа в Данж", drops:"Древний манипулятор и запуск небесных столбов", tip:"Не бей ложные копии во время ритуала дракона." },
    { id:"astrum-deus", era:"hard", type:"Каламити", name:"Аструм Деус", en:"Astrum Deus", q:24, art:"assets/boss-sprites/astrum-deus.png", where:"Астральный маяк ночью", when:"Перед Лунным лордом", summon:"Помести Сердце титана в Астральный маяк", drops:"Открытие астральной руды и Эфирное ядро", tip:"Два астральных червя особенно уязвимы для пронзания." },
    { id:"moon-lord", era:"hard", type:"Ваниль", name:"Лунный лорд", en:"Moon Lord", q:24, art:"assets/boss-sprites/vanilla/moon-lord.png", where:"Поверхность", when:"Финал ванильной части прохождения", summon:"Победи четыре столба либо используй Небесную печать", drops:"Люминит, Небесная луковица и постлунная прогрессия", tip:"Победа открывает основную половину эндгейма Calamity." },

    { id:"profaned-guardians", era:"post", type:"Каламити", name:"Осквернённые стражи", en:"Profaned Guardians", q:25, art:"assets/boss-sprites/profaned-guardians.png", where:"Святые земли или Преисподняя", when:"Первый постлунный ритуал", summon:"Используй Осквернённый осколок", drops:"Осквернённое ядро и материалы Провиденс", tip:"Три стража знакомят с атаками следующего босса." },
    { id:"dragonfolly", era:"post", type:"Каламити", name:"Драконье безумие", en:"Dragonfolly", q:25, art:"assets/boss-sprites/dragonfolly.png", where:"Джунгли", when:"До или сразу после Провиденс", summon:"Используй Экзотический феромон в джунглях", drops:"Сияющие перья и драконье оружие", tip:"Не путай его призыв с яйцом Ярона." },
    { id:"providence", era:"post", type:"Каламити", name:"Провиденс", en:"Providence, the Profaned Goddess", q:25, art:"assets/boss-sprites/providence.png", where:"Святые земли днём или Преисподняя ночью", when:"Главный ранний постлунный босс", summon:"Используй Осквернённое ядро", drops:"Божественные геоды и открытие юэлибума", tip:"Место боя меняет набор атак и награды." },
    { id:"ceaseless-void", era:"post", type:"Каламити", name:"Неугасимая пустота", en:"Ceaseless Void", q:26, art:"assets/boss-sprites/ceaseless-void.png", where:"Данж", when:"После Провиденс", summon:"Используй Метку Провиденс в Данже", drops:"Тёмная плазма", tip:"Следи за тёмными энергиями и не покидай Данж." },
    { id:"storm-weaver", era:"post", type:"Каламити", name:"Ткач бурь", en:"Storm Weaver", q:26, art:"assets/boss-sprites/storm-weaver.png", where:"Космос", when:"После Провиденс", summon:"Используй Метку Провиденс в космосе", drops:"Бронированный панцирь", tip:"Первая фаза требует ударов по хвосту, затем броня разрушается." },
    { id:"signus", era:"post", type:"Каламити", name:"Сигнус", en:"Signus, Envoy of the Devourer", q:26, art:"assets/boss-sprites/signus.png", where:"Преисподняя", when:"После Провиденс", summon:"Используй Метку Провиденс в Преисподней", drops:"Крутящийся эфир", tip:"Быстрые телепорты требуют широкой горизонтальной арены." },
    { id:"polterghast", era:"post", type:"Каламити", name:"Полтергаст", en:"Polterghast", q:26, art:"assets/boss-sprites/polterghast.png", where:"Подземный Данж", when:"После трёх вестников", summon:"Используй Некроплазменный маяк или убей достаточно Фантомных духов", drops:"Гибельные души и Эктосердце на Возмездии", tip:"Заранее расчисти большую комнату внутри Данжа." },
    { id:"old-duke", era:"post", type:"Каламити", name:"Старый герцог", en:"The Old Duke", q:26, art:"assets/boss-sprites/old-duke.png", where:"Сернистое море", when:"После Полтергаста, третий кислотный дождь", summon:"Дойди до конца третьего кислотного дождя либо используй Кровавого червя", drops:"Позднее сернистое оружие", tip:"Опциональный, но чрезвычайно быстрый босс." },
    { id:"devourer-of-gods", era:"post", type:"Каламити", name:"Пожиратель богов", en:"The Devourer of Gods", q:27, art:"assets/boss-sprites/devourer-of-gods.png", where:"Очень длинная открытая арена", when:"После Полтергаста и вестников", summon:"Используй Космического червя", drops:"Космилитовые слитки и усиленные события", tip:"Арена на сотни блоков и точное уклонение обязательны." },
    { id:"yharon", era:"post", type:"Каламити", name:"Ярон", en:"Yharon, Dragon of Rebirth", q:28, art:"assets/boss-sprites/yharon.png", where:"Джунгли", when:"После Пожирателя богов", summon:"Используй Благословенное яйцо феникса", drops:"Фрагменты души Ярона, ауриковая руда и Крылья возрождения", tip:"Не покидай джунгли и готовься к двум фазам." },
    { id:"exo-mechs", era:"end", type:"Каламити", name:"Экзо-мехи", en:"Exo Mechs", q:29, art:"assets/boss-sprites/exo-mechs.png", where:"Гигантская открытая арена", when:"После Ярона", summon:"Полностью собери Взломостойку и активируй Ауриковую охлаждающую ячейку", drops:"Экзо-призмы и доступ к финальной кузне", tip:"Выбери начального меха и заранее реши порядок целей." },
    { id:"supreme-calamitas", era:"end", type:"Каламити", name:"Верховная ведьма Каламитас", en:"Supreme Witch, Calamitas", q:29, art:"assets/boss-sprites/supreme-calamitas.png", where:"Алтарь проклятых", when:"После Ярона", summon:"Положи Пепел бедствия на Алтарь проклятых", drops:"Пепел уничтожения и Каламитас как городская НПС", tip:"Финальная проверка уклонения; множество попыток является нормой." },

    { id:"primordial-wyrm", era:"end", type:"Скрытый босс", name:"Первозданный змей", en:"Primordial Wyrm", q:30, art:"assets/boss-sprites/primordial-wyrm.png", where:"Четвёртый слой Бездны", when:"Скрытый эндгейм-бой после подготовки к Бездне", summon:"Используй Жезл раздора в Бездне", drops:"Пушка палтуса и полный набор добычи Эйдолонского змея", tip:"Не относится к обязательной прогрессии и требует лучшего снаряжения." },
    { id:"hekate", era:"end", type:"Скрытый босс", name:"XB-∞ Геката", en:"XB-∞ Hekate", q:30, art:"assets/boss-sprites/hekate.png", where:"Особый мир Get fixed boi", when:"Шуточный скрытый маршрут вместо Экзо-мехов", summon:"В мире Get fixed boi вставь Кровавую вену в полностью собранную Взломостойку и нажми «Вызвать»", drops:"Обычная добыча Экзо-мехов и гарантированный Лавовый куриный бульон", tip:"Существует только на секретном сиде Get fixed boi." },
    { id:"permafrost", era:"end", type:"Скрытый босс", name:"Верховный ультрамаг Пермафрост", en:"Supreme Ultramage, Permafrost", q:30, art:"assets/lex/calamity/archmage.png", where:"Особый мир Get fixed boi", when:"Шуточный скрытый маршрут вместо Верховной ведьмы", summon:"В мире Get fixed boi взаимодействуй с Алтарём проклятых, держа Вкусное мясо", drops:"Обычная добыча Верховной ведьмы и гарантированная Ледяная сосулька", tip:"Существует только на секретном сиде Get fixed boi." },
    { id:"the-lorde", era:"end", type:"Скрытый босс", name:"THE LORDE", en:"THE LORDE", q:30, art:"assets/npc-sprites/the-lorde.png", where:"Особый мир Get fixed boi", when:"Скрытый шуточный эндгейм-бой", summon:"Используй предмет NO по маршруту особого сида", drops:"Подозрительно выглядящий NO U", tip:"Комбинирует атаки разных боссов и существует только на Get fixed boi." }
  ];

  CODEX.bosses = bosses.map((boss, index) => ({ ...boss, n: index + 1, kind: boss.type === "Скрытый босс" ? "hidden" : "boss" }));
  CODEX.bossFavoriteMigration = {
    1:["king-slime"], 2:["desert-scourge"], 3:["eye-of-cthulhu"], 4:["crabulon"],
    5:["eater-of-worlds","brain-of-cthulhu"], 6:["hive-mind","perforators"], 7:["queen-bee"], 8:["deerclops"],
    9:["skeletron"], 10:["slime-god"], 11:["wall-of-flesh"], 12:["queen-slime"], 13:["cryogen"],
    14:["twins","destroyer","skeletron-prime"], 15:["aquatic-scourge"], 16:["brimstone-elemental"],
    17:["calamitas-clone"], 18:["plantera"], 19:["leviathan-anahita"], 20:["astrum-aureus"], 21:["golem"],
    22:["plaguebringer-goliath"], 23:["ravager"], 24:["duke-fishron","empress-of-light"], 25:["astrum-deus"],
    26:["moon-lord"], 27:["profaned-guardians"], 28:["dragonfolly"], 29:["providence"],
    30:["ceaseless-void","storm-weaver","signus"], 31:["polterghast"], 32:["old-duke"],
    33:["devourer-of-gods"], 34:["yharon"], 35:["exo-mechs"], 36:["supreme-calamitas"]
  };

  CODEX.minis = [
    { id:"giant-clam", kind:"mini", era:"pre", type:"Мини-босс", name:"Гигантский моллюск", en:"Giant Clam", q:6, art:"assets/boss-sprites/giant-clam.png", where:"Затонувшее море", when:"После Пустынного бича; получает новые атаки в хардмоде", summon:"Редко появляется естественно в Затонувшем море", drops:"Навикамень, гигантская жемчужина, оружие моря и оболочка моллюска", tip:"Победа позволяет Морскому королю поселиться в мире." },
    { id:"cragmaw-mire", kind:"mini", era:"hard", type:"Мини-босс", name:"Трясинная пасть", en:"Cragmaw Mire", q:16, art:"assets/boss-sprites/cragmaw-mire.png", where:"Сернистое море во время кислотного дождя", when:"После Водного бича", summon:"Появляется естественно на втором уровне кислотного дождя", drops:"Отработанный топливный контейнер и Ядерный топливный стержень", tip:"На третьем уровне дождя получает усиленную вторую фазу." },
    { id:"great-sand-shark", kind:"mini", era:"hard", type:"Мини-босс", name:"Великая песчаная акула", en:"Great Sand Shark", q:20, art:"assets/boss-sprites/great-sand-shark.png", where:"Пустыня во время песчаной бури", when:"После Плантеры", summon:"Убей десять песчаных акул либо используй Ядро песчаной бури", drops:"Великая чешуя", tip:"Двигается сквозь песок и призывает обычных песчаных акул." },
    { id:"mauler", kind:"mini", era:"post", type:"Мини-босс", name:"Изверг", en:"Mauler", q:26, art:"assets/npc-sprites/mauler.png", where:"Сернистое море во время кислотного дождя", when:"После Полтергаста", summon:"Появляется естественно на третьем уровне кислотного дождя", drops:"Серная кислотная пушка и акульи плавники", tip:"Сначала пассивен, но становится крайне быстрым после провокации." },
    { id:"nuclear-terror", kind:"mini", era:"post", type:"Мини-босс", name:"Ядерный ужас", en:"Nuclear Terror", q:26, art:"assets/npc-sprites/nuclear-terror.png", where:"Сернистое море во время кислотного дождя", when:"После Полтергаста", summon:"Появляется естественно на третьем уровне кислотного дождя", drops:"Фосфоресцирующая перчатка и Гамма-сердце", tip:"Телепортируется и выпускает плотные очереди радиоактивных снарядов." }
  ];
})();
