/* Official Calamity NPC textures from pinned commit 1a8cebd27ec5615316b78f71973446b5528d2b78. */
window.CALAMITY_NPC_ART = {
  "Acid Eel": "assets/npc-sprites/acid-eel.png",
  "Anahita": "assets/npc-sprites/anahita.png",
  "Anthozoan Crab": "assets/npc-sprites/anthozoan-crab.png",
  "Aquatic Urchin": "assets/npc-sprites/aquatic-urchin.png",
  "Aries": "assets/npc-sprites/aries.png",
  "Astraglomerate": "assets/npc-sprites/astraglomerate.png",
  "Astral Slime": "assets/npc-sprites/astral-slime.png",
  "Astrum Aureus": "assets/npc-sprites/astrum-aureus.png",
  "Atlas": "assets/npc-sprites/atlas.png",
  "Belching Coral": "assets/npc-sprites/belching-coral.png",
  "Blinded Angler": "assets/npc-sprites/blinded-angler.png",
  "Bloatfish": "assets/npc-sprites/bloatfish.png",
  "Bohldohr": "assets/npc-sprites/bohldohr.png",
  "Brimstone Elemental": "assets/npc-sprites/brimstone-elemental.png",
  "Burrower": "assets/npc-sprites/burrower.png",
  "Calamitas Clone": "assets/npc-sprites/calamitas-clone.png",
  "Calamity Eye": "assets/npc-sprites/calamity-eye.png",
  "Chaotic Puffer": "assets/npc-sprites/chaotic-puffer.png",
  "Clam": "assets/npc-sprites/clam.png",
  "Cloud Elemental": "assets/npc-sprites/cloud-elemental.png",
  "Cnidrion": "assets/npc-sprites/cnidrion.png",
  "Colossal Squid": "assets/npc-sprites/colossal-squid.png",
  "Crabulon": "assets/npc-sprites/crabulon.png",
  "Cragmaw Mire": "assets/npc-sprites/cragmaw-mire.png",
  "Crimulan Blight Slime": "assets/npc-sprites/crimulan-blight-slime.png",
  "Cuttlefish": "assets/npc-sprites/cuttlefish.png",
  "Despair Stone": "assets/npc-sprites/despair-stone.png",
  "Ebonian Blight Slime": "assets/npc-sprites/ebonian-blight-slime.png",
  "Eidolist": "assets/npc-sprites/eidolist.png",
  "Flak Crab": "assets/npc-sprites/flak-crab.png",
  "Fusion Feeder": "assets/npc-sprites/fusion-feeder.png",
  "Ghost Bell": "assets/npc-sprites/ghost-bell.png",
  "Giant Clam": "assets/npc-sprites/giant-clam.png",
  "Giant Squid": "assets/npc-sprites/giant-squid.png",
  "Gnasher": "assets/npc-sprites/gnasher.png",
  "Great Sand Shark": "assets/npc-sprites/great-sand-shark.png",
  "Hadarian": "assets/npc-sprites/hadarian.png",
  "Heat Spirit": "assets/npc-sprites/heat-spirit.png",
  "Horrible Hog": "assets/npc-sprites/horrible-hog.png",
  "Ice Clasper": "assets/npc-sprites/ice-clasper.png",
  "Impious Immolator": "assets/npc-sprites/impious-immolator.png",
  "Infernal Congealment": "assets/npc-sprites/infernal-congealment.png",
  "Laserfish": "assets/npc-sprites/laserfish.png",
  "Luminous Corvina": "assets/npc-sprites/luminous-corvina.png",
  "Mantis": "assets/npc-sprites/mantis.png",
  "Mantis Shrimp": "assets/npc-sprites/mantis-shrimp.png",
  "Mauler": "assets/npc-sprites/mauler.png",
  "Mirage Jelly": "assets/npc-sprites/mirage-jelly.png",
  "Nova": "assets/npc-sprites/nova.png",
  "Nuclear Terror": "assets/npc-sprites/nuclear-terror.png",
  "Nuclear Toad": "assets/npc-sprites/nuclear-toad.png",
  "Orthocera": "assets/npc-sprites/orthocera.png",
  "Overloaded Soldier": "assets/npc-sprites/overloaded-soldier.png",
  "Pestilent Slime": "assets/npc-sprites/pestilent-slime.png",
  "Plague Charger": "assets/npc-sprites/plague-charger.png",
  "PlagueChargerLarge": "assets/npc-sprites/plaguechargerlarge.png",
  "Polterghast": "assets/npc-sprites/polterghast.png",
  "Prism-Back": "assets/npc-sprites/prism-back.png",
  "Radiator": "assets/npc-sprites/radiator.png",
  "Reaper Shark": "assets/npc-sprites/reaper-shark.png",
  "Renegade Warlock": "assets/npc-sprites/renegade-warlock.png",
  "Rimehound": "assets/npc-sprites/rimehound.png",
  "Rotdog": "assets/npc-sprites/rotdog.png",
  "Scorn Eater": "assets/npc-sprites/scorn-eater.png",
  "Shockstorm Shuttle": "assets/npc-sprites/shockstorm-shuttle.png",
  "Sightseer Collider": "assets/npc-sprites/sightseer-collider.png",
  "Sightseer Spitter": "assets/npc-sprites/sightseer-spitter.png",
  "Signus": "assets/npc-sprites/signus.png",
  "Skyfin": "assets/npc-sprites/skyfin.png",
  "Slab Crab": "assets/npc-sprites/slab-crab.png",
  "Soul Slurper": "assets/npc-sprites/soul-slurper.png",
  "Stellar Culex": "assets/npc-sprites/stellar-culex.png",
  "Stormlion": "assets/npc-sprites/stormlion.png",
  "Sulphurous Skater": "assets/npc-sprites/sulphurous-skater.png",
  "THE LORDE": "assets/npc-sprites/the-lorde.png",
  "Trilobite": "assets/npc-sprites/trilobite.png",
  "Wulfrum Amplifier": "assets/npc-sprites/wulfrum-amplifier.png",
  "Wulfrum Drone": "assets/npc-sprites/wulfrum-drone.png",
  "Wulfrum Gyrator": "assets/npc-sprites/wulfrum-gyrator.png",
  "Wulfrum Hovercraft": "assets/npc-sprites/wulfrum-hovercraft.png",
  "Wulfrum Rover": "assets/npc-sprites/wulfrum-rover.png"
};
