/* Официальные спрайты: Calamity repo + ванильные иконки инвентаря. */
window.CODEX = window.CODEX || {};
CODEX.sprites = {
  "Стартовый мешок": "assets/sprites/StarterBag.png",
  "Wooden Sword / Bow / Staff из мешка": "assets/sprites/Wooden_Sword.png",
  "Верстак": "assets/sprites/Work_Bench.png",
  "Печь": "assets/sprites/Furnace.png",
  "Железная / свинцовая наковальня": "assets/sprites/Iron_Anvil.png",
  "Кровать": "assets/sprites/Bed.png",
  "Life Crystal": "assets/sprites/Life_Crystal.png",
  "Hermes / Flurry / Sailfish / Dunerider Boots": "assets/sprites/Hermes_Boots.png",
  "Cloud / Blizzard / Sandstorm in a Bottle": "assets/sprites/Cloud_in_a_Bottle.png",
  "Grappling Hook": "assets/sprites/Grappling_Hook.png",
  "Wulfrum Metal Scrap": "assets/sprites/WulfrumMetalScrap.png",
  "Energy Core": "assets/sprites/EnergyCore.png",
  "Wulfrum Hat & Goggles": "assets/sprites/WulfrumHat.png",
  "Wulfrum Jacket": "assets/sprites/WulfrumJacket.png",
  "Wulfrum Overalls": "assets/sprites/WulfrumOveralls.png",
  "Wulfrum Controller": "assets/sprites/WulfrumController.png",
  "Wulfrum Blade / Screwdriver": "assets/sprites/WulfrumScrewdriver.png",
  "Wulfrum Bow / Blunderbuss": "assets/sprites/WulfrumBlunderbuss.png",
  "Wulfrum Prosthesis / Staff": "assets/sprites/WulfrumProsthesis.png",
  "Wulfrum Knife": "assets/sprites/WulfrumKnife.png",
  "Rover Drive": "assets/sprites/RoverDrive.png",
  "Power Cell Factory": "assets/sprites/PowerCellFactoryItem.png",
  "Charging Station": "assets/sprites/ChargingStationItem.png",
  "Dubious Plating / Mysterious Circuitry": "assets/sprites/DubiousPlating.png",
  "Lab Seeking Mechanism": "assets/sprites/LabSeekingMechanism.png",
  "Enchanted Sword / Terragrim": "assets/sprites/Enchanted_Sword.png",
  "Starfury": "assets/sprites/Starfury.png",
  "Аксессуар святилища": "assets/sprites/LuxorsGift.png",
  "Sea Prism": "assets/sprites/SeaPrism.png",
  "Prism Shard": "assets/sprites/SeaPrism.png",
  "Schematic (Sunken Sea)": "assets/sprites/EncryptedSchematicSunkenSea.png",
  "Slime Crown": "assets/sprites/Slime_Crown.png",
  "Slimy Saddle / Hook": "assets/sprites/Slimy_Saddle.png",
  "Stormlion Mandible": "assets/sprites/StormlionMandible.png",
  "Antlion Mandible": "assets/sprites/Antlion_Mandible.png",
  "Desert Medallion": "assets/sprites/DesertMedallion.png",
  "Pearl Shard": "assets/sprites/PearlShard.png",
  "Sea Remains": "assets/sprites/SeaRemains.png",
  "Victide Breastplate": "assets/sprites/VictideBreastplate.png",
  "Victide Greaves": "assets/sprites/VictideGreaves.png",
  "Victide Shellmet": "assets/sprites/VictideHeadMelee.png",
  "Victide Coral Turban": "assets/sprites/VictideHeadRanged.png",
  "Victide Hermit Helmet": "assets/sprites/VictideHeadMagic.png",
  "Victide Mask": "assets/sprites/VictideHeadSummon.png",
  "Victide Headcrab": "assets/sprites/VictideHeadRogue.png",
  "Urchin Mace": "assets/sprites/UrchinMace.png",
  "Reed Blowgun": "assets/sprites/ReedBlowgun.png",
  "Coral Spout": "assets/sprites/CoralSpout.png",
  "Cnidarian": "assets/sprites/Cnidarian.png",
  "Fishbone Boomerang": "assets/sprites/FishboneBoomerang.png",
  "Greatbay Pickaxe": "assets/sprites/GreatbayPickaxe.png",
  "Reefclaw Hamaxe": "assets/sprites/ReefclawHamaxe.png",
  "Shield of the Ocean": "assets/sprites/ShieldoftheOcean.png",
  "Amidias' Blessing": "assets/sprites/AmidiasPendant.png",
  "Amidias' Pendant / Spark": "assets/sprites/AmidiasPendant.png",
  "Suspicious Looking Eye": "assets/sprites/Suspicious_Looking_Eye.png",
  "Shield of Cthulhu": "assets/sprites/Shield_of_Cthulhu.png",
  "Sulphuric Scale": "assets/sprites/SulphuricScale.png",
  "Sulphurous armor": "assets/sprites/SulphurousBreastplate.png",
  "Acid Gun / Toxibow": "assets/sprites/AcidGun.png",
  "Blood Orb": "assets/sprites/BloodOrb.png",
  "Decapodita Sprout": "assets/sprites/DecapoditaSprout.png",
  "Fungal Clump": "assets/sprites/FungalClump.png",
  "Mycoroot / Hyphae Rod / Fungicide": "assets/sprites/Mycoroot.png",
  "Mushroom Plasma Root": "assets/sprites/MushroomPlasmaRoot.png",
  "Worm Food": "assets/sprites/Worm_Food.png",
  "Bloody Spine": "assets/vanilla-sprites/1331.png",
  "Musket / The Undertaker": "assets/sprites/Musket.png",
  "Vilethorn / Crimson Rod": "assets/sprites/Vilethorn.png",
  "Ball O' Hurt / The Meatball": "assets/sprites/Ball_O_Hurt.png",
  "Aerialite Ore": "assets/sprites/AerialiteOre.png",
  "Aerospec armor": "assets/sprites/AerospecBreastplate.png",
  "Harpy Ring": "assets/sprites/HarpyRing.png",
  "Feather Crown": "assets/sprites/FeatherCrown.png",
  "Abeemination": "assets/sprites/Abeemination.png",
  "Bee Gun / Bee's Knees / Hive-Five": "assets/sprites/Bee_Gun.png",
  "Cobalt Shield": "assets/sprites/Cobalt_Shield.png",
  "Shadow Key": "assets/sprites/Shadow_Key.png",
  "Alchemy Table": "assets/sprites/Alchemy_Table.png",
  "Muramasa / Aqua Scepter / Magic Missile / Handgun": "assets/sprites/Muramasa.png",
  "Water Bolt": "assets/sprites/Water_Bolt.png",
  "Decryption Computer": "assets/sprites/DecryptionComputer.png",
  "Оружие 1 слоя Бездны": "assets/sprites/DepthCrusher.png",
  "Arctic Diving Gear": "assets/sprites/Arctic_Diving_Gear.png",
  "Blighted Gel": "assets/sprites/BlightedGel.png",
  "Overloaded Sludge": "assets/sprites/OverloadedSludge.png",
  "Purified Gel": "assets/sprites/PurifiedGel.png",
  "Statigel armor": "assets/sprites/StatigelArmor.png",
  "Gelitive / Overloaded weapons": "assets/sprites/GeliticBlade.png",
  "Electrolyte Gel Pack": "assets/sprites/ElectrolyteGelPack.png",
  "Guide Voodoo Doll": "assets/sprites/Guide_Voodoo_Doll.png",
  "Emblem класса / Rogue Emblem": "assets/sprites/RogueEmblem.png",
  "Pwnhammer": "assets/sprites/Pwnhammer.png",
  "Warrior / Ranger / Sorcerer / Summoner / Rogue Emblem": "assets/sprites/Warrior_Emblem.png",
  "Cobalt / Palladium armor": "assets/sprites/Cobalt_Breastplate.png",
  "Essence of Sunlight": "assets/sprites/EssenceofSunlight.png",
  "Essence of Eleum": "assets/sprites/EssenceofEleum.png",
  "Essence of Havoc": "assets/sprites/EssenceofHavoc.png",
  "Starblight Soot": "assets/sprites/StarblightSoot.png",
  "Comet Shard": "assets/sprites/CometShard.png",
  "Mollusk Husk": "assets/sprites/MolluskHusk.png",
  "Crystal Assassin armor": "assets/sprites/Crystal_Assassin_Shirt.png",
  "Frostspark / Lightning / Terraspark Boots": "assets/sprites/Terraspark_Boots.png",
  "Крылья (любые первые)": "assets/sprites/SkylineWings.png",
  "Cryo Key": "assets/sprites/CryoKey.png",
  "Cryonic Ore / Bar": "assets/sprites/CryonicOre.png",
  "Daedalus armor": "assets/sprites/DaedalusBreastplate.png",
  "Ледяное оружие Криогена": "assets/sprites/Avalanche.png",
  "Seafood": "assets/sprites/Seafood.png",
  "Hallowed Bar / Hallowed armor": "assets/sprites/Hallowed_Bar.png",
  "Sanguine Tangerine": "assets/sprites/SanguineTangerine.png",
  "Long Ranged Sensor Array": "assets/sprites/LongRangedSensorArray.png",
  "Soul of Sight": "assets/sprites/Soul_of_Sight.png",
  "Soul of Might": "assets/vanilla-sprites/548.png",
  "Soul of Fright": "assets/vanilla-sprites/547.png",
  "Unholy Core": "assets/sprites/UnholyCore.png",
  "Charred Idol": "assets/sprites/CharredIdol.png",
  "Серное оружие элементаля": "assets/sprites/Brimlance.png",
  "Eye of Desolation": "assets/sprites/EyeofDesolation.png",
  "Ashes of Calamity": "assets/sprites/Calamity.png",
  "Solar Veil": "assets/sprites/SolarVeil.png",
  "Оружие клона": "assets/sprites/Animosity.png",
  "Portabulb": "assets/sprites/Portabulb.png",
  "Perennial Ore / Bar": "assets/sprites/PerennialOre.png",
  "Core of Calamity": "assets/sprites/Calamity.png",
  "Chlorophyte armor / оружие": "assets/sprites/Chlorophyte_Plate_Mail.png",
  "Grand Scale": "assets/sprites/GrandScale.png",
  "Seedler / Pygmy Staff / Venus Magnum / Leaf Blower": "assets/sprites/Seedler.png",
  "Abyssal Diving Gear": "assets/sprites/AbyssalDivingGear.png",
  "Aquatic Emblem": "assets/sprites/AquaticEmblem.png",
  "Оружие Левиафана и Анахиты": "assets/sprites/Atlantis.png",
  "Depth Cells": "assets/sprites/DepthCells.png",
  "Lumenyl": "assets/sprites/Lumenyl.png",
  "Planty Mush": "assets/sprites/PlantyMush.png",
  "Astral Chunk": "assets/sprites/AstralChunk.png",
  "Heavenfallen Stardisk": "assets/sprites/HeavenfallenStardisk.png",
  "Starlight Fuel Cell": "assets/sprites/StarlightFuelCell.png",
  "Астральное оружие врагов": "assets/sprites/AstralPike.png",
  "Lihzahrd Power Cell": "assets/sprites/Lihzahrd_Power_Cell.png",
  "Scoria Ore / Bar": "assets/sprites/ScoriaOre.png",
  "Hydrothermic armor": "assets/sprites/HydrothermicArmor.png",
  "Life Alloy": "assets/sprites/LifeAlloy.png",
  "Miracle Fruit": "assets/sprites/MiracleFruit.png",
  "Plague Cell Canister": "assets/sprites/PlagueCellCanister.png",
  "Advanced Display": "assets/sprites/AdvancedDisplay.png",
  "Rift Reeler": "assets/sprites/RiftReeler.png",
  "Призыв PBG": "assets/sprites/Abombination.png",
  "Infected Armor Plating": "assets/sprites/InfectedArmorPlating.png",
  "Plaguebringer / Plague Reaper armor": "assets/sprites/PlaguebringerCarapace.png",
  "Чумные пушки / клинки / посохи": "assets/sprites/PestilentDefiler.png",
  "Fleshy Geode": "assets/sprites/FleshyGeode.png",
  "Infernal Blood": "assets/sprites/InfernalBlood.png",
  "Tsunami / Razorblade Typhoon / Tempest Staff / Flairon": "assets/sprites/Tsunami.png",
  "Empress оружия / Terraprisma": "assets/sprites/Terraprisma.png",
  "Soaring Insignia / Wings Empress": "assets/sprites/Soaring_Insignia.png",
  "Titan Heart": "assets/sprites/TitanHeart.png",
  "Astral Ore / Bar": "assets/sprites/AstralOre.png",
  "Ethereal Core": "assets/sprites/EtherealCore.png",
  "Astral armor": "assets/sprites/AstralBreastplate.png",
  "Celestial Sigil / столбы": "assets/sprites/Celestial_Sigil.png",
  "Luminite / Lunar Fragments": "assets/sprites/Luminite_Bar.png",
  "Celestial Onion": "assets/sprites/CelestialOnion.png",
  "Exodium Cluster": "assets/sprites/ExodiumCluster.png",
  "Solar / Vortex / Nebula / Stardust / Empyrean armor": "assets/sprites/EmpyreanCloak.png",
  "Unholy Essence": "assets/sprites/UnholyEssence.png",
  "Profaned Core": "assets/sprites/ProfanedCore.png",
  "Divine Geode": "assets/sprites/DivineGeode.png",
  "Uelibloom Ore / Bar": "assets/sprites/UelibloomOre.png",
  "Tarragon armor": "assets/sprites/TarragonBreastplate.png",
  "Tainted Cloudberry": "assets/sprites/TaintedCloudberry.png",
  "Bloodstone": "assets/sprites/Bloodstone.png",
  "Brimrose": "assets/sprites/Brimrose.png",
  "Effulgent Feather": "assets/sprites/EffulgentFeather.png",
  "Red Lightning Container": "assets/sprites/RedLightningContainer.png",
  "Профанное оружие": "assets/sprites/HolyCollider.png",
  "Mark of Providence": "assets/sprites/MarkofProvidence.png",
  "Armored Shell": "assets/sprites/ArmoredShell.png",
  "Dark Plasma": "assets/sprites/DarkPlasma.png",
  "Twisting Nether": "assets/sprites/TwistingNether.png",
  "Ruinous Soul": "assets/sprites/RuinousSoul.png",
  "Bloodflare armor": "assets/sprites/BloodflareBodyArmor.png",
  "Omega Blue armor": "assets/sprites/OmegaBlueChestplate.png",
  "Phantom Heart": "assets/sprites/PhantomHeart.png",
  "Ectoheart": "assets/sprites/Ectoheart.png",
  "Reaper Tooth": "assets/sprites/ReaperTooth.png",
  "Cosmic Worm": "assets/sprites/CosmicWorm.png",
  "Cosmilite Bar": "assets/sprites/CosmiliteBar.png",
  "Cosmic Anvil": "assets/sprites/CosmicAnvilItem.png",
  "Nightmare Fuel": "assets/sprites/NightmareFuel.png",
  "Endothermic Energy": "assets/sprites/EndothermicEnergy.png",
  "Darksun Fragment": "assets/sprites/DarksunFragment.png",
  "Ascendant Spirit Essence": "assets/sprites/AscendantSpiritEssence.png",
  "God Slayer armor": "assets/sprites/GodSlayerChestplate.png",
  "Silva armor": "assets/sprites/SilvaArmor.png",
  "Murasama": "assets/sprites/Murasama.png",
  "Omega Healing Potion": "assets/sprites/OmegaHealingPotion.png",
  "Blessed Phoenix Egg": "assets/sprites/YharonEgg.png",
  "Yharon Soul Fragment": "assets/sprites/YharonSoulFragment.png",
  "Wings of Rebirth": "assets/sprites/WingsofRebirth.png",
  "Seraph Tracers": "assets/sprites/SeraphTracers.png",
  "Auric Ore / Bar": "assets/sprites/AuricOre.png",
  "Auric Tesla armor": "assets/sprites/AuricTeslaBodyArmor.png",
  "Sacred Strawberry": "assets/sprites/SacredStrawberry.png",
  "Auric Quantum Cooling Cell": "assets/sprites/AuricQuantumCoolingCell.png",
  "Altar of the Accursed": "assets/sprites/AltarOfTheAccursedItem.png",
  "Драконье оружие Ярона": "assets/sprites/DragonRage.png",
  "Exo Prism": "assets/sprites/ExoPrism.png",
  "Ashes of Annihilation": "assets/sprites/AshesofAnnihilation.png",
  "Draedon's Forge": "assets/sprites/DraedonsForge.png",
  "Miracle Matter": "assets/sprites/MiracleMatter.png",
  "Exo-оружие (Exoblade и др.)": "assets/sprites/Exoblade.png",
  "Shadowspec Bar": "assets/sprites/ShadowspecBar.png",
  "Demonshade armor": "assets/sprites/DemonshadeBreastplate.png",
  "Зачарование ведьмы": "assets/sprites/Calamity.png",
  "Terminus": "assets/sprites/Terminus.png",
  "Rock": "assets/sprites/Rock.png",
  "Добыча Первозданного змея": "assets/sprites/HalibutCannon.png",
  "Flying Dragon": "assets/vanilla-sprites/3827.png",
  "Sky Dragon's Fury": "assets/vanilla-sprites/3858.png",
  "Aerial Bane": "assets/vanilla-sprites/3859.png",
  "Betsy's Wrath": "assets/vanilla-sprites/3870.png",
  "Ancient Manipulator": "assets/vanilla-sprites/3549.png",
  "Bloody Vein": "assets/item-sprites/BloodyVein.png",
  "Nuclear Fuel Rod": "assets/item-sprites/NuclearFuelRod.png",
  "Spent Fuel Container": "assets/item-sprites/SpentFuelContainer.png",
  "Sandstorm's Core": "assets/item-sprites/SandstormsCore.png",
  "Eidolon Tablet": "assets/item-sprites/EidolonTablet.png",
  "Sulphuric Acid Cannon": "assets/item-sprites/SulphuricAcidCannon.png",
  "Phosphorescent Gauntlet": "assets/item-sprites/PhosphorescentGauntlet.png",
  "Gamma Heart": "assets/item-sprites/GammaHeart.png",
  "Lava Chicken Broth": "assets/item-sprites/LavaChickenBroth.png",
  "Delicious Meat": "assets/item-sprites/DeliciousMeat.png",
  "Coldheart Icicle": "assets/item-sprites/ColdheartIcicle.png",
  "Halibut Cannon": "assets/item-sprites/HalibutCannon.png",
  "Eidolic Wail": "assets/item-sprites/EidolicWail.png",
  "Grand Dad": "assets/item-sprites/GrandDad.png",
  "Abyss Shell Fossil": "assets/item-sprites/AbyssShellFossil.png",
  "NO": "assets/item-sprites/NO.png",
  "Suspicious Looking NO U": "assets/item-sprites/SuspiciousLookingNOU.png",
  "Codebreaker (каркас)": "assets/sprites/CodebreakerBase.png"
};

CODEX.spriteOf = function (it) {
  const S = CODEX.sprites || {};
  if (!it) return "";
  if (typeof it === "string") return S[it] || "";
  return S[it.name] || S[it.nameRu] || (it.sprite && S[it.sprite]) || "";
};
